# ---------------------------------------------------------------------------
# Stage 05: the rank-one diagnostic -- does the solve-or-guess model actually
# fit these raters?
#
# WHY YOU NEED THIS
#   Stage 04 will happily produce solving probabilities for any set of raters.
#   It cannot tell you whether the model that generated those numbers is a
#   sensible description of your data. This stage is the check, and it is not
#   optional: the kappa-ratio is only interpretable if the model holds.
#
# THE IDEA
#   The model's central claim is that agreement between two raters comes from
#   the product of their solving probabilities. That implies a strong,
#   testable shape for the whole agreement matrix: every off-diagonal entry
#   must be a chance floor plus a rank-one term,
#
#       A_ab = c + (1 - c) * p_a * p_b
#
#   Rank one means the entire matrix of who-agrees-with-whom is generated by a
#   single number per rater. That is a lot of structure to impose, and real
#   data can violate it -- for instance if two raters agree with each other far
#   more than their individual abilities predict, which is what shared bias or
#   copying looks like.
#
#   We measure the departure with the residual sum of squares
#   T = sum_{a<b} (A_ab - c - (1-c) p_a p_b)^2, then ask whether the observed T
#   is unusually large. To know what "large" means we need T's distribution
#   when the model is TRUE, so we generate it: simulate datasets from the
#   fitted model, refit, and recompute T each time. The p-value is the fraction
#   of simulated datasets with T at least as large as the real one.
#
# HOW TO READ IT
#   A LARGE p-value means the observed agreement is consistent with the model.
#   Note the logic runs opposite to a familiar significance test: here you
#   WANT to fail to reject. And failing to reject is reassurance, not proof --
#   with only a handful of raters this test has little power, so it catches
#   gross violations and misses subtle ones.
#
# INPUT   results/<experiment>/rater_labels_long.csv, written by stage 04
#         (the same labels actually fitted, abstain policy already applied)
# OUTPUT  results/<experiment>/rank_one_diagnostic.csv
#
# USAGE
#   Rscript code/05_rank_one_diagnostic.R                           # worked example
#   Rscript code/05_rank_one_diagnostic.R experiments/my_study.yaml
# ---------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
})
source(here("code", "config.R"))

cfg        <- load_experiment()
experiment <- cfg$id
SYSTEM     <- cfg$analysis$system_rater_id
RATERS     <- cfg$rater_order
m          <- length(RATERS)
B          <- cfg$analysis$bootstrap_B

# Seeded before any simulation, so the p-value is reproducible.
set.seed(cfg$analysis$seed_diagnostic)

source(here("code", "em", "spectral_initializer.R"))
source(here("code", "em", "tidy_solve_or_guess_fast.R"))

results_dir <- here("results", experiment)
long_path   <- file.path(results_dir, "rater_labels_long.csv")
if (!file.exists(long_path)) {
  stop("Missing ", long_path, "\n  Run stage 04 first -- this diagnostic tests ",
       "the fit that stage 04 produced.", call. = FALSE)
}
long <- read_csv(long_path, show_col_types = FALSE)

message("Experiment: ", experiment)
message("Raters: ", paste(RATERS, collapse = ", "))

# --- observed agreement matrix, A_ab = P(rater a and rater b give the same label)
wide <- long |>
  pivot_wider(names_from = rater_id, values_from = evaluation) |>
  select(all_of(RATERS))

agreement_matrix <- function(W) {
  M <- matrix(1, m, m, dimnames = list(RATERS, RATERS))
  for (a in 1:m) for (b in 1:m) if (a != b) M[a, b] <- mean(W[[a]] == W[[b]])
  M
}
A_obs <- agreement_matrix(wide)

# --- fit the rank-one + chance form to an agreement matrix, return T ---------
# Optimised on the logit scale so the probabilities stay in (0, 1) without
# constrained optimisation. Returns the residual sum of squares, our statistic.
fit_rank_one <- function(A, p_init, c_init) {
  ut <- upper.tri(A)
  obj <- function(par) {
    c0 <- plogis(par[1]); p <- plogis(par[-1])
    pred <- c0 + (1 - c0) * outer(p, p)
    sum((A[ut] - pred[ut])^2)
  }
  clamp <- function(x) pmin(pmax(x, 1e-3), 1 - 1e-3)
  init <- c(qlogis(clamp(c_init)), qlogis(clamp(p_init)))
  optim(init, obj, method = "BFGS")$value
}

# --- refit the full model here, to get the parameters we simulate from -------
# Stage 04 already fitted this, but it writes out only the solving
# probabilities. The parametric bootstrap also needs each rater's guessing
# distribution and the class prior, so we refit rather than adding those to
# stage 04's outputs.
evaluations <- long |> select(item_id, rater_id, evaluation)
fit <- solve_or_guess_fast(evaluations, system_rater_id = SYSTEM, verbose = FALSE)

p_hat <- setNames(
  vapply(RATERS, function(r) plogis(fit$rater_ability$estimate[
    fit$rater_ability$rater_id == r & fit$rater_ability$parameter_id == "intercept"]), numeric(1)),
  RATERS)

ev_levels <- sort(unique(fit$guessing_distribution$evaluation))
d <- length(ev_levels)

# tau: the estimated prior over true labels -- how common each class is.
tau <- vapply(ev_levels, function(e)
  fit$class_distribution$prior_prob[fit$class_distribution$evaluation == e][1], numeric(1))
tau <- tau / sum(tau)

# Pi: one guessing distribution per rater, the labels they fall back on when
# they do not solve. Rows are renormalised to guard against drift.
Pi <- matrix(0, m, d, dimnames = list(RATERS, ev_levels))
for (r in RATERS) for (e in ev_levels)
  Pi[r, e] <- fit$guessing_distribution$probability[
    fit$guessing_distribution$rater_id == r & fit$guessing_distribution$evaluation == e]
Pi <- Pi / rowSums(Pi)

n <- nrow(wide)

# Chance agreement if everyone guessed from the class prior: the natural
# starting point for c, and the floor the rank-one term sits on top of.
c_init <- sum(tau^2)
T_obs  <- fit_rank_one(A_obs, p_init = p_hat, c_init = c_init)

# --- parametric bootstrap: simulate the model, recompute T -------------------
# One replicate: draw a true label for each item from tau, then have each rater
# either solve it (reporting the truth) or guess from their own distribution --
# which is the generative story of the model, run forwards.
sim_T <- function() {
  Y <- sample(d, n, replace = TRUE, prob = tau)
  R <- matrix(0L, n, m, dimnames = list(NULL, RATERS))
  for (a in 1:m) {
    solved <- runif(n) < p_hat[a]
    R[, a] <- ifelse(solved, Y, sample(d, n, replace = TRUE, prob = Pi[a, ]))
  }
  A <- matrix(1, m, m); for (a in 1:m) for (b in 1:m) if (a != b) A[a, b] <- mean(R[, a] == R[, b])
  fit_rank_one(A, p_init = p_hat, c_init = c_init)
}
message(sprintf("Simulating null distribution (B = %d)...", B))
T_boot  <- replicate(B, sim_T())
p_value <- mean(T_boot >= T_obs)

out <- tibble(statistic = "rank_one_RSS", T_obs = T_obs, B = B, p_value = p_value)
write_csv(out, file.path(results_dir, "rank_one_diagnostic.csv"))

cat("\n================  Rank-one diagnostic  ================\n")
cat(sprintf("  T_observed = %.5f\n", T_obs))
cat(sprintf("  parametric bootstrap p-value (B = %d) = %.3f\n", B, p_value))
cat(sprintf("  %s the solve-or-guess model at 0.05\n",
            if (p_value < 0.05) "REJECTS" else "fails to reject"))
if (p_value >= 0.05) {
  cat("  (Reassurance, not proof: with few raters this test has limited power.)\n")
} else {
  cat("  The agreement structure is NOT consistent with the model. Treat the\n")
  cat("  solving probabilities from stage 04 as unreliable, and check for\n")
  cat("  shared bias between raters or a vague codebook.\n")
}
cat(sprintf("\nWrote %s\n", file.path(results_dir, "rank_one_diagnostic.csv")))
